import { StoryPage } from "./types";
import { jsPDF } from "jspdf";
import JSZip from "jszip";

export async function exportMarkdown(
  title: string,
  pages: StoryPage[]
): Promise<void> {
  const slug = slugify(title);
  const zip = new JSZip();
  const imgFolder = zip.folder("images")!;

  // -- Markdown (for VS Code / GitHub) --
  let md = `<div align="center">\n\n# ${title}\n\n---\n\n</div>\n\n`;

  // -- HTML (for browsers) --
  let htmlPages = "";

  for (const page of pages) {
    let imgName = "";
    if (page.image.data) {
      const ext = page.image.mimeType.split("/")[1] || "png";
      imgName = `page-${page.pageNumber}.${ext}`;
      imgFolder.file(imgName, page.image.data, { base64: true });

      md += `<div align="center">\n\n`;
      md += `![Page ${page.pageNumber}](images/${imgName})\n\n`;
      md += `</div>\n\n`;
    }

    md += `<div style="text-align:justify">\n\n${page.poem}\n\n</div>\n\n`;
    md += `<div align="center">\n\n${page.pageNumber}\n\n---\n\n</div>\n\n`;

    // HTML page section
    const escapedPoem = page.poem
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
    htmlPages += `
      <section class="story-page">
        ${imgName ? `<div class="painting"><img src="images/${imgName}" alt="Page ${page.pageNumber}" /></div>` : ""}
        <div class="prose">${escapedPoem}</div>
        <div class="page-num">${page.pageNumber}</div>
        <div class="divider"></div>
      </section>`;
  }

  md += `<div align="center">\n\n*Generated by Luna*\n\n</div>\n`;

  const html = buildHTML(title, htmlPages);

  zip.file(`${slug}.md`, md);
  zip.file(`${slug}.html`, html);
  const blob = await zip.generateAsync({ type: "blob" });
  downloadBlob(blob, `${slug}.zip`);
}

function buildHTML(title: string, pagesHTML: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${title}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;1,300;1,400&display=swap');

  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    background: #FFFFFF;
    color: #1A1A1F;
    font-family: 'Cormorant Garamond', 'Times New Roman', serif;
    min-height: 100vh;
  }

  /* Vignette */
  body::after {
    content: '';
    position: fixed;
    inset: 0;
    pointer-events: none;
    background: radial-gradient(ellipse at center, transparent 40%, rgba(26,26,31,0.05) 100%);
  }

  .container { max-width: 800px; margin: 0 auto; padding: 0 24px; }

  /* Title */
  header {
    text-align: center;
    padding: 64px 0 16px;
  }
  header h1 {
    font-size: 3rem;
    font-weight: 300;
    letter-spacing: -0.02em;
    color: #1A1A1F;
  }
  header .divider {
    width: 96px;
    height: 1px;
    background: rgba(138,138,148,0.3);
    margin: 24px auto 0;
  }

  /* Story pages */
  .story-page {
    padding: 48px 0 64px;
  }
  .painting {
    width: 75%;
    margin: 0 auto 40px;
  }
  .painting img {
    width: 100%;
    height: auto;
    display: block;
    box-shadow: 0 10px 30px -4px rgba(26,26,31,0.25);
  }
  .prose {
    max-width: 580px;
    margin: 0 auto;
    font-size: 1.2rem;
    line-height: 1.85;
    text-align: justify;
    text-indent: 1.5em;
    color: #1A1A1F;
    padding: 0 24px;
  }
  .page-num {
    text-align: center;
    margin-top: 32px;
    font-family: system-ui, sans-serif;
    font-size: 0.7rem;
    color: #8A8A94;
    text-transform: uppercase;
    letter-spacing: 0.3em;
  }
  .story-page > .divider {
    width: 64px;
    height: 1px;
    background: rgba(138,138,148,0.2);
    margin: 16px auto 0;
  }

  /* Footer */
  footer {
    text-align: center;
    padding: 48px 0;
    border-top: 1px solid #E8E8EC;
    font-family: system-ui, sans-serif;
    font-size: 0.75rem;
    color: #8A8A94;
    letter-spacing: 0.15em;
    text-transform: uppercase;
  }
</style>
</head>
<body>
<div class="container">
  <header>
    <h1>${title}</h1>
    <div class="divider"></div>
  </header>
  ${pagesHTML}
  <footer>Generated by Luna</footer>
</div>
</body>
</html>`;
}

export async function exportPDF(
  title: string,
  pages: StoryPage[]
): Promise<void> {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 25;
  const contentWidth = pageWidth - margin * 2;
  const cx = pageWidth / 2;

  // -- Title page --
  // Centered title — Times (closest built-in to Cormorant Garamond)
  pdf.setFont("times", "normal");
  pdf.setFontSize(36);
  pdf.setTextColor(26, 26, 31);
  const titleLines = pdf.splitTextToSize(title, contentWidth);
  const titleBlockHeight = titleLines.length * 14;
  const titleY = pageHeight * 0.4 - titleBlockHeight / 2;
  pdf.text(titleLines, cx, titleY, { align: "center", lineHeightFactor: 1.3 });

  // Thin divider
  const dividerY = titleY + titleBlockHeight + 6;
  pdf.setDrawColor(138, 138, 148);
  pdf.setLineWidth(0.25);
  pdf.line(cx - 16, dividerY, cx + 16, dividerY);

  // Subtitle — sans-serif for contrast
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(138, 138, 148);
  pdf.text("Generated by Luna", cx, dividerY + 8, { align: "center" });

  // -- Story pages --
  for (const page of pages) {
    pdf.addPage();
    pdf.setTextColor(26, 26, 31);

    // Painting — centered at ~75% content width to match on-screen proportions
    const imgWidth = contentWidth * 0.75;
    const imgX = (pageWidth - imgWidth) / 2;
    let y = margin + 4;

    if (page.image.data) {
      const imgData = `data:${page.image.mimeType};base64,${page.image.data}`;
      const imgHeight = imgWidth * 0.65;

      // Subtle shadow (a light gray rectangle offset behind the image)
      pdf.setFillColor(230, 230, 234);
      pdf.rect(imgX + 1.5, y + 1.5, imgWidth, imgHeight, "F");

      pdf.addImage(imgData, "JPEG", imgX, y, imgWidth, imgHeight);
      y += imgHeight + 14;
    }

    // Prose — centered narrow column, justified serif text
    const proseWidth = contentWidth * 0.65;
    const proseX = (pageWidth - proseWidth) / 2;
    pdf.setFont("times", "normal");
    pdf.setFontSize(11);
    const textLines: string[] = pdf.splitTextToSize(page.poem, proseWidth);
    const lineHeight = 5.5;
    for (let i = 0; i < textLines.length; i++) {
      const line = textLines[i].trim();
      const isLastLine = i === textLines.length - 1;
      // Justify all lines except the last one in the paragraph
      if (!isLastLine && line.length > 0) {
        const words = line.split(/\s+/);
        if (words.length > 1) {
          const totalWordWidth = words.reduce(
            (sum, w) => sum + pdf.getTextWidth(w),
            0
          );
          const extraSpace =
            (proseWidth - totalWordWidth) / (words.length - 1);
          let cursorX = proseX;
          for (const word of words) {
            pdf.text(word, cursorX, y);
            cursorX += pdf.getTextWidth(word) + extraSpace;
          }
        } else {
          pdf.text(line, proseX, y);
        }
      } else {
        pdf.text(line, proseX, y);
      }
      y += lineHeight;
    }

    // Page number — centered near bottom, sans-serif
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(138, 138, 148);
    pdf.text(String(page.pageNumber), cx, pageHeight - margin, {
      align: "center",
    });

    // Bottom divider line
    pdf.setDrawColor(200, 200, 206);
    pdf.setLineWidth(0.2);
    pdf.line(cx - 10, pageHeight - margin + 3, cx + 10, pageHeight - margin + 3);
  }

  pdf.save(`${slugify(title)}.pdf`);
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
