import { StoryPage } from "./types";
import { jsPDF } from "jspdf";

export function exportMarkdown(title: string, pages: StoryPage[]): void {
  let md = `# ${title}\n\n`;

  for (const page of pages) {
    md += `---\n\n`;
    md += `### ${page.pageNumber}\n\n`;
    md += `${page.poem}\n\n`;
    if (page.image.data) {
      md += `![Page ${page.pageNumber}](data:${page.image.mimeType};base64,${page.image.data})\n\n`;
    }
  }

  md += `---\n\n*Generated by Luna*\n`;

  const blob = new Blob([md], { type: "text/markdown" });
  downloadBlob(blob, `${slugify(title)}.md`);
}

export async function exportPDF(
  title: string,
  pages: StoryPage[]
): Promise<void> {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  // Title page
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(32);
  const titleLines = pdf.splitTextToSize(title, contentWidth);
  const titleY = pageHeight / 2 - titleLines.length * 8;
  pdf.text(titleLines, pageWidth / 2, titleY, { align: "center" });

  // Divider line
  pdf.setDrawColor(180, 180, 190);
  pdf.setLineWidth(0.3);
  pdf.line(pageWidth / 2 - 20, titleY + 14, pageWidth / 2 + 20, titleY + 14);

  // Subtitle
  pdf.setFontSize(10);
  pdf.setTextColor(138, 138, 148);
  pdf.text("Generated by Luna", pageWidth / 2, titleY + 22, {
    align: "center",
  });

  // Story pages
  for (const page of pages) {
    pdf.addPage();
    pdf.setTextColor(26, 26, 31);
    let y = margin;

    // Image
    if (page.image.data) {
      const imgData = `data:${page.image.mimeType};base64,${page.image.data}`;
      const imgWidth = contentWidth;
      const imgHeight = imgWidth * 0.65;
      pdf.addImage(imgData, "JPEG", margin, y, imgWidth, imgHeight);
      y += imgHeight + 10;
    }

    // Prose
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);
    const textLines = pdf.splitTextToSize(page.poem, contentWidth);
    pdf.text(textLines, margin, y);
    y += textLines.length * 6;

    // Page number at bottom
    pdf.setFontSize(9);
    pdf.setTextColor(138, 138, 148);
    pdf.text(String(page.pageNumber), pageWidth / 2, pageHeight - 12, {
      align: "center",
    });
  }

  pdf.save(`${slugify(title)}.pdf`);
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
